name: Weather
version: 2.0.3
main: tgwaste\Weather\Main
api: 5.0.0
author: tgwaste
commands:
  weather:
    usage: "/weather <clear|rain|thunder|query> [seconds]"
    description: "Weather commands"
    permission: weather.operator
permissions:
  weather.operator:
    description: allow using weather commands
    default: op
