name: Weather
version: 1.0.5
main: tgwaste\Weather\Main
api: 4.0.0
author: tgwaste
commands:
  weather:
    usage: "/weather <clear|rain|thunder|query> [seconds]"
    description: "Weather commands"
    permission: weather.operator
permissions:
  weather.operator:
    description: allow using weather commands
    default: op
